[book]
title = "Özgür Yazılım Derneği Güvenlik Rehberi"
authors = ["Özgür Yazılım Derneği"]
language = "tr"
multilingual = false
src = "src"

[preprocessor.toc]
command = "mdbook-toc"
renderer = ["html"]
max-level = 4

[output.html]
theme = "src/theme"
default-theme = "rust"
git-repository-url = "https://git.oyd.org.tr/oyd/guvenlik"
git-repository-icon = "fa-git" #|fa-git-square

[output.html.search]
enable = true


